name: condo_plus
description: Um gerenciador de condomínio.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  google_fonts: null
  intl: ^0.18.0
  path_provider: ^2.0.13
  rive: ^0.10.3
  skeletons: ^0.0.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - json/
    - assets/

  fonts:
    - family: SanFrancisco
      fonts:
        - asset: assets/fonts/san-francisco/SFPRODISPLAYULTRALIGHTITALIC.OTF
        - asset: assets/fonts/san-francisco/SFPRODISPLAYTHINITALIC.OTF
        - asset: assets/fonts/san-francisco/SFPRODISPLAYSEMIBOLDITALIC.OTF
        - asset: assets/fonts/san-francisco/SFPRODISPLAYREGULAR.OTF
        - asset: assets/fonts/san-francisco/SFPRODISPLAYMEDIUM.OTF
        - asset: assets/fonts/san-francisco/SFPRODISPLAYLIGHTITALIC.OTF
        - asset: assets/fonts/san-francisco/SFPRODISPLAYHEAVYITALIC.OTF
        - asset: assets/fonts/san-francisco/SFPRODISPLAYBOLD.OTF
        - asset: assets/fonts/san-francisco/SFPRODISPLAYBLACKITALIC.OTF

    - family: Comfortaa
      fonts:
        - asset: assets/fonts/comfortaa/Comfortaa-Bold.ttf
        - asset: assets/fonts/comfortaa/Comfortaa-Light.ttf
        - asset: assets/fonts/comfortaa/Comfortaa-Medium.ttf
        - asset: assets/fonts/comfortaa/Comfortaa-Regular.ttf
        - asset: assets/fonts/comfortaa/Comfortaa-SemiBold.ttf