name: condo_plus
description: Um gerenciador de condomínio.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  cloud_firestore: ^4.8.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.2
  firebase_core: ^2.10.0
  flutter:
    sdk: flutter
  get: ^4.6.5
  google_fonts: null
  intl: ^0.18.0
  path_provider: ^2.0.13
  rive: ^0.10.3
  skeletons: ^0.0.3
  image_picker: ^0.8.7+5
  image_cropper: ^4.0.1
  mask_text_input_formatter: ^2.4.0
  firebase_storage: ^11.2.1
  uuid: ^3.0.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - json/
    - assets/images/avisos/
    - assets/images/icon/IOS/
    - assets/images/icon/
    - assets/images/icons/
    - assets/images/memoji/

  fonts:
  - family: SFPro
    fonts:
      - asset: assets/fonts/Sf-Pro/SF-Pro.ttf
      - asset: assets/fonts/Sf-Pro/SF-Pro-Italic.ttf
        style: italic

  - family: Comfortaa
    fonts:
      - asset: assets/fonts/Comfortaa/Comfortaa-Bold.ttf
      - asset: assets/fonts/Comfortaa/Comfortaa-Light.ttf
      - asset: assets/fonts/Comfortaa/Comfortaa-Medium.ttf
      - asset: assets/fonts/Comfortaa/Comfortaa-Regular.ttf
      - asset: assets/fonts/Comfortaa/Comfortaa-SemiBold.ttf
