// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp7fgZJ_yyWd7mMYvbQ4hMR9b0pMLsEeA',
    appId: '1:935319084802:android:8263151cc00cc63dda6c1b',
    messagingSenderId: '935319084802',
    projectId: 'condo-plus',
    databaseURL: 'https://condo-plus-default-rtdb.firebaseio.com',
    storageBucket: 'condo-plus.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTaMykgkLtmwtkgMoAYqkACHqNYrfX5GY',
    appId: '1:935319084802:ios:5b6818156218603ada6c1b',
    messagingSenderId: '935319084802',
    projectId: 'condo-plus',
    databaseURL: 'https://condo-plus-default-rtdb.firebaseio.com',
    storageBucket: 'condo-plus.appspot.com',
    iosClientId: '935319084802-2umpdjngocg67us7750jomfj37d26l0k.apps.googleusercontent.com',
    iosBundleId: 'com.pauloricardo.2503230416condoPlus',
  );
}
